build:
  environment:
    php:
      version: '8.0'
  nodes:
    analysis:
      dependencies:
        before:
          - composer require friendsofphp/php-cs-fixer
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: ./vendor/bin/php-cs-fixer fix /home/scrutinizer/build
            use_website_config: false
checks:
  php: true
coding_style:
  php: {  }
filter: {  }
