build:
  environment:
    php:
      version: '8.0'
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
checks:
  php: true
coding_style:
  php: {  }
filter: {  }
