language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=origin/master

before_script:
  - php-cgi --version
  - sudo apt-get -qq install nginx
  - php-cgi -b 127.0.0.1:9000 &
  - sudo nginx -c vendor/nginx.conf -p "$PWD/"
  - php vendor/vendors.php

notifications:
  email:
    - friendsofsymfony-dev@googlegroups.com
