name: CI

on:
    pull_request:
    push:
        branches:
            - master
            - 2.x
            - 3.x

jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'
                    - '8.2'
                    - '8.3'
                symfony-versions: [false]
                include:
                    -   description: 'Symfony 4.*'
                        php: '7.4'
                        symfony-versions: '^4.4'
                    -   description: 'Symfony 5.*'
                        php: '8.1'
                        symfony-versions: '^5.4'
                    -   description: 'Symfony 6.*'
                        php: '8.2'
                        symfony-versions: '^6.4'
        name: PHP ${{ matrix.php }} ${{ matrix.description }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/cache@v4
              with:
                  path: ~/.composer/cache/files
                  key: composer-${{ matrix.php }}-${{ matrix.symfony-versions }}-${{ hashFiles('composer.json') }}
                  restore-keys: |
                    composer-${{ matrix.php }}-
                    composer-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install symfony/flex
              run: composer config --global --no-plugins allow-plugins.symfony/flex true && composer global require symfony/flex
              if: matrix.symfony-versions

            - name: Install dependencies
              env:
                SYMFONY_REQUIRE: ${{ matrix.symfony-versions }}
              run: composer update

            - name: Install PHPUnit
              run: ./vendor/bin/simple-phpunit install

            - name: Run PHPUnit tests
              run: |
                ./vendor/bin/simple-phpunit
